import { Career, Interest, PersonalityTrait, PersonalityType, Skill } from "@/types";

export const SKILLS: Skill[] = [
  { id: "s1", name: "Problem Solving", category: "Cognitive" },
  { id: "s2", name: "Critical Thinking", category: "Cognitive" },
  { id: "s3", name: "Creativity", category: "Cognitive" },
  { id: "s4", name: "Communication", category: "Social" },
  { id: "s5", name: "Leadership", category: "Social" },
  { id: "s6", name: "Teamwork", category: "Social" },
  { id: "s7", name: "Time Management", category: "Organizational" },
  { id: "s8", name: "Project Management", category: "Organizational" },
  { id: "s9", name: "Programming", category: "Technical" },
  { id: "s10", name: "Data Analysis", category: "Technical" },
  { id: "s11", name: "Design", category: "Creative" },
  { id: "s12", name: "Writing", category: "Creative" },
  { id: "s13", name: "Research", category: "Academic" },
  { id: "s14", name: "Public Speaking", category: "Communication" },
  { id: "s15", name: "Adaptability", category: "Personal" },
  { id: "s16", name: "Attention to Detail", category: "Personal" },
];

export const INTERESTS: Interest[] = [
  { id: "i1", name: "Technology", category: "STEM" },
  { id: "i2", name: "Science", category: "STEM" },
  { id: "i3", name: "Mathematics", category: "STEM" },
  { id: "i4", name: "Engineering", category: "STEM" },
  { id: "i5", name: "Art", category: "Creative" },
  { id: "i6", name: "Music", category: "Creative" },
  { id: "i7", name: "Writing", category: "Creative" },
  { id: "i8", name: "Business", category: "Professional" },
  { id: "i9", name: "Finance", category: "Professional" },
  { id: "i10", name: "Marketing", category: "Professional" },
  { id: "i11", name: "Healthcare", category: "Service" },
  { id: "i12", name: "Education", category: "Service" },
  { id: "i13", name: "Social Work", category: "Service" },
  { id: "i14", name: "Sports", category: "Physical" },
  { id: "i15", name: "Nature", category: "Environment" },
  { id: "i16", name: "Travel", category: "Lifestyle" },
];

export const ACADEMIC_SUBJECTS = [
  { id: "a1", name: "Mathematics", score: 0 },
  { id: "a2", name: "Science", score: 0 },
  { id: "a3", name: "English", score: 0 },
  { id: "a4", name: "Social Studies", score: 0 },
  { id: "a5", name: "Arts", score: 0 },
];

export const PERSONALITY_TRAITS: PersonalityTrait[] = [
  {
    id: "p1",
    title: "Energy",
    description: "How do you prefer to interact with the world?",
    options: {
      a: "I gain energy from social interactions (Extrovert)",
      b: "I gain energy from solitary time (Introvert)",
    },
    answer: null,
  },
  {
    id: "p2",
    title: "Information",
    description: "How do you prefer to process information?",
    options: {
      a: "I focus on concrete facts and details (Sensing)",
      b: "I focus on patterns and possibilities (Intuition)",
    },
    answer: null,
  },
  {
    id: "p3",
    title: "Decisions",
    description: "How do you prefer to make decisions?",
    options: {
      a: "I prioritize logic and consistency (Thinking)",
      b: "I prioritize people and harmony (Feeling)",
    },
    answer: null,
  },
  {
    id: "p4",
    title: "Structure",
    description: "How do you prefer to organize your life?",
    options: {
      a: "I prefer planning and organization (Judging)",
      b: "I prefer flexibility and spontaneity (Perceiving)",
    },
    answer: null,
  },
];

export const PERSONALITY_TYPES: PersonalityType[] = [
  {
    code: "INTJ",
    title: "Architect",
    description: "Strategic thinkers with a plan for everything",
    careers: ["Software Engineer", "Data Scientist", "Strategic Planner", "Architect"],
  },
  {
    code: "INTP",
    title: "Logician",
    description: "Innovative inventors with an unquenchable thirst for knowledge",
    careers: ["Research Scientist", "Software Developer", "Mathematician", "Philosopher"],
  },
  {
    code: "ENTJ",
    title: "Commander",
    description: "Bold, imaginative and strong-willed leaders",
    careers: ["Executive", "Entrepreneur", "Lawyer", "Management Consultant"],
  },
  {
    code: "ENTP",
    title: "Debater",
    description: "Smart and curious thinkers who cannot resist an intellectual challenge",
    careers: ["Entrepreneur", "Creative Director", "Attorney", "Consultant"],
  },
  {
    code: "INFJ",
    title: "Advocate",
    description: "Quiet and mystical, yet very inspiring and tireless idealists",
    careers: ["Counselor", "HR Manager", "Writer", "Psychologist"],
  },
  {
    code: "INFP",
    title: "Mediator",
    description: "Poetic, kind and altruistic people, always eager to help a good cause",
    careers: ["Writer", "Counselor", "Social Worker", "Artist"],
  },
  {
    code: "ENFJ",
    title: "Protagonist",
    description: "Charismatic and inspiring leaders, able to mesmerize their listeners",
    careers: ["Teacher", "HR Director", "Marketing Manager", "Public Relations Specialist"],
  },
  {
    code: "ENFP",
    title: "Campaigner",
    description: "Enthusiastic, creative and sociable free spirits",
    careers: ["Journalist", "Marketing Creative", "Event Planner", "Counselor"],
  },
  {
    code: "ISTJ",
    title: "Logistician",
    description: "Practical and fact-minded individuals, whose reliability cannot be doubted",
    careers: ["Accountant", "Project Manager", "Financial Analyst", "Military Officer"],
  },
  {
    code: "ISFJ",
    title: "Defender",
    description: "Very dedicated and warm protectors, always ready to defend their loved ones",
    careers: ["Nurse", "Elementary Teacher", "HR Specialist", "Administrative Assistant"],
  },
  {
    code: "ESTJ",
    title: "Executive",
    description: "Excellent administrators, unsurpassed at managing things or people",
    careers: ["Business Administrator", "Project Manager", "Sales Manager", "Judge"],
  },
  {
    code: "ESFJ",
    title: "Consul",
    description: "Extraordinarily caring, social and popular people",
    careers: ["Healthcare Worker", "Teacher", "Sales Representative", "Event Planner"],
  },
  {
    code: "ISTP",
    title: "Virtuoso",
    description: "Bold and practical experimenters, masters of all kinds of tools",
    careers: ["Engineer", "Mechanic", "Pilot", "Forensic Scientist"],
  },
  {
    code: "ISFP",
    title: "Adventurer",
    description: "Flexible and charming artists, always ready to explore and experience something new",
    careers: ["Artist", "Designer", "Veterinarian", "Physical Therapist"],
  },
  {
    code: "ESTP",
    title: "Entrepreneur",
    description: "Smart, energetic and very perceptive people",
    careers: ["Entrepreneur", "Sales Executive", "Marketing Specialist", "Detective"],
  },
  {
    code: "ESFP",
    title: "Entertainer",
    description: "Spontaneous, energetic and enthusiastic people",
    careers: ["Event Planner", "Sales Representative", "Tour Guide", "Performer"],
  },
];

export const CAREERS: Career[] = [
  {
    id: "c1",
    title: "Software Engineer",
    description: "Design, develop, and maintain software systems and applications.",
    requiredSkills: ["Programming", "Problem Solving", "Critical Thinking"],
    matchingTags: ["Technology", "Mathematics", "Engineering"],
    educationRequired: "Bachelor's degree in Computer Science or related field",
    averageSalary: "$105,000",
    growthOutlook: "Excellent",
  },
  {
    id: "c2",
    title: "Data Scientist",
    description: "Analyze and interpret complex data to help organizations make better decisions.",
    requiredSkills: ["Data Analysis", "Programming", "Critical Thinking"],
    matchingTags: ["Technology", "Mathematics", "Science"],
    educationRequired: "Master's degree in Data Science, Statistics, or related field",
    averageSalary: "$120,000",
    growthOutlook: "Excellent",
  },
  {
    id: "c3",
    title: "UX/UI Designer",
    description: "Create user-friendly interfaces and experiences for digital products.",
    requiredSkills: ["Design", "Creativity", "Communication"],
    matchingTags: ["Technology", "Art", "Psychology"],
    educationRequired: "Bachelor's degree in Design, HCI, or related field",
    averageSalary: "$85,000",
    growthOutlook: "Good",
  },
  {
    id: "c4",
    title: "Marketing Manager",
    description: "Develop and implement marketing strategies to promote products or services.",
    requiredSkills: ["Communication", "Creativity", "Project Management"],
    matchingTags: ["Business", "Marketing", "Communication"],
    educationRequired: "Bachelor's degree in Marketing, Business, or related field",
    averageSalary: "$90,000",
    growthOutlook: "Good",
  },
  {
    id: "c5",
    title: "Financial Analyst",
    description: "Analyze financial data and make recommendations for investment decisions.",
    requiredSkills: ["Data Analysis", "Critical Thinking", "Attention to Detail"],
    matchingTags: ["Finance", "Mathematics", "Business"],
    educationRequired: "Bachelor's degree in Finance, Economics, or related field",
    averageSalary: "$95,000",
    growthOutlook: "Good",
  },
  {
    id: "c6",
    title: "Healthcare Administrator",
    description: "Manage healthcare facilities, services, and staff to ensure quality care.",
    requiredSkills: ["Leadership", "Project Management", "Communication"],
    matchingTags: ["Healthcare", "Business", "Social Work"],
    educationRequired: "Bachelor's degree in Healthcare Administration or related field",
    averageSalary: "$100,000",
    growthOutlook: "Excellent",
  },
  {
    id: "c7",
    title: "Teacher",
    description: "Educate students in various subjects and help them develop knowledge and skills.",
    requiredSkills: ["Communication", "Patience", "Creativity"],
    matchingTags: ["Education", "Social Work", "Communication"],
    educationRequired: "Bachelor's degree in Education or subject area",
    averageSalary: "$60,000",
    growthOutlook: "Stable",
  },
  {
    id: "c8",
    title: "Environmental Scientist",
    description: "Study environmental problems and develop solutions to protect the environment.",
    requiredSkills: ["Research", "Critical Thinking", "Problem Solving"],
    matchingTags: ["Science", "Nature", "Engineering"],
    educationRequired: "Bachelor's degree in Environmental Science or related field",
    averageSalary: "$75,000",
    growthOutlook: "Good",
  },
  {
    id: "c9",
    title: "Graphic Designer",
    description: "Create visual concepts to communicate ideas that inspire, inform, or captivate consumers.",
    requiredSkills: ["Design", "Creativity", "Attention to Detail"],
    matchingTags: ["Art", "Technology", "Communication"],
    educationRequired: "Bachelor's degree in Graphic Design or related field",
    averageSalary: "$55,000",
    growthOutlook: "Stable",
  },
  {
    id: "c10",
    title: "Human Resources Specialist",
    description: "Recruit, screen, interview, and place workers, and handle employee relations.",
    requiredSkills: ["Communication", "Teamwork", "Attention to Detail"],
    matchingTags: ["Business", "Social Work", "Psychology"],
    educationRequired: "Bachelor's degree in Human Resources, Business, or related field",
    averageSalary: "$65,000",
    growthOutlook: "Good",
  },
  {
    id: "c11",
    title: "Architect",
    description: "Design buildings and structures, considering both aesthetics and functionality.",
    requiredSkills: ["Design", "Problem Solving", "Attention to Detail"],
    matchingTags: ["Engineering", "Art", "Mathematics"],
    educationRequired: "Bachelor's degree in Architecture",
    averageSalary: "$80,000",
    growthOutlook: "Stable",
  },
  {
    id: "c12",
    title: "Psychologist",
    description: "Study cognitive, emotional, and social processes and behavior by observing, interpreting, and recording how people relate to one another and to their environments.",
    requiredSkills: ["Research", "Communication", "Critical Thinking"],
    matchingTags: ["Healthcare", "Social Work", "Science"],
    educationRequired: "Doctoral degree in Psychology",
    averageSalary: "$85,000",
    growthOutlook: "Good",
  },
];